### ISSUE TITLE
doctemplates-0.2.1 does not compile with ghc 8.4.1

### ISSUE THREAD

**Issue by peti** [jgm/doctemplates#2]
The error is:

~~~
src/Text/DocTemplates.hs:104:27: error:
    • No instance for (Semigroup Template)
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Monoid Template)
    |
104 |                  deriving Monoid
    |                           ^^^^^^
~~~

**Comment by jgm** [comment]
I think the commit I just pushed will fix the issue, but I
don't have a ghc 8.4.1 setup here to test.  If you're able
to test and confirm this works, that would be helpful.

+++ Peter Simons [Mar 09 18 19:18 ]:

**Comment by peti** [comment]
Yes, the new version compiles fine. Thank you very much for the quick fix!
